# Generated by Django 5.2.3 on 2025-06-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causal_app', '0005_knowledgegraph_knowledgegraphtrip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeGraphTrip',
            new_name='KnowledgeGraphTriple',
        ),
    ]
