# Generated by Django 5.1.4 on 2025-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causal_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="causaledge",
            name="directed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="causalgraph",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
