# Generated by Django 5.1.4 on 2025-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causal_app", "0002_causaledge_directed_causalgraph_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="causalgraph",
            name="data_file",
            field=models.FileField(blank=True, null=True, upload_to="datasets/"),
        ),
    ]
