# Generated by Django 5.1.4 on 2026-08-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causal_app", "0008_causalgraph_node_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="causalgraph",
            name="cleaned_file",
            field=models.FileField(
                blank=True, null=True, upload_to="datasets/cleaned/"
            ),
        ),
        migrations.AddField(
            model_name="causalgraph",
            name="cleaning_plan",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
