# Generated by Django 5.1.4 on 2026-09-17 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


# The workspace tables used to belong to a separate "p0" app. An installation that ran that
# version still holds its rows in p0_* tables; carry them over before those tables are dropped.
# Column names are identical in both schemas. graphownership and artifact rows get fresh ids,
# since nothing references them by id. Where the old app never existed this copies nothing.
OLD_TABLES = [
    ("workspace", "token_hash, created_at, expires_at, busy, deleting"),
    ("graphownership", "graph_id, workspace_id, sample_id, cleaning_history"),
    ("artifact", "workspace_id, graph_id, storage_name"),
    ("runrecord", "id, workspace_id, graph_id, created_at, analysis_key, operation, payload"),
    ("llmpermit", "id, workspace_id, payload_hash, operation, expires_at, used"),
]


def copy_rows_from_p0_tables(apps, schema_editor):
    connection = schema_editor.connection
    present = set(connection.introspection.table_names())
    with connection.cursor() as cursor:
        for table, columns in OLD_TABLES:
            if f"p0_{table}" in present:
                cursor.execute(f"INSERT INTO causal_app_{table} ({columns}) SELECT {columns} FROM p0_{table}")


class Migration(migrations.Migration):

    dependencies = [
        ("causal_app", "0009_causalgraph_cleaned_file_causalgraph_cleaning_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "token_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("busy", models.BooleanField(default=False)),
                ("deleting", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RunRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_key", models.CharField(db_index=True, max_length=64)),
                ("operation", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(blank=True, max_length=64)),
                ("cleaning_history", models.JSONField(default=list)),
                (
                    "graph",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership",
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graphs",
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_name", models.CharField(max_length=500)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="causal_app.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "storage_name"),
                        name="workspace_unique_artifact",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_rows_from_p0_tables, migrations.RunPython.noop),
        # The old tables are no longer read; drop them and the p0 app's migration bookkeeping.
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS p0_artifact",
                "DROP TABLE IF EXISTS p0_graphownership",
                "DROP TABLE IF EXISTS p0_llmpermit",
                "DROP TABLE IF EXISTS p0_runrecord",
                "DROP TABLE IF EXISTS p0_workspace",
                "DELETE FROM django_migrations WHERE app = 'p0'",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
