# Generated by Django 5.1.4 on 2026-09-17 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causal_app", "0009_causalgraph_cleaned_file_causalgraph_cleaning_plan"),
    ]

    operations = [
        # These models used to live in a separate "p0" app. Its tables only ever held 24-hour
        # session data, so start fresh here and remove the leftovers where they exist.
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS p0_artifact",
                "DROP TABLE IF EXISTS p0_graphownership",
                "DROP TABLE IF EXISTS p0_llmpermit",
                "DROP TABLE IF EXISTS p0_runrecord",
                "DROP TABLE IF EXISTS p0_workspace",
                "DELETE FROM django_migrations WHERE app = 'p0'",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "token_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("busy", models.BooleanField(default=False)),
                ("deleting", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RunRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_key", models.CharField(db_index=True, max_length=64)),
                ("operation", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(blank=True, max_length=64)),
                ("cleaning_history", models.JSONField(default=list)),
                (
                    "graph",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership",
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graphs",
                        to="causal_app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_name", models.CharField(max_length=500)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="causal_app.causalgraph",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="causal_app.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "storage_name"),
                        name="workspace_unique_artifact",
                    )
                ],
            },
        ),
    ]
